using MathGame.Answer; using MathGame.Board; using MathGame.BoardResolution; using MathGame.Fever; using MathGame.StageSession; using MathGame.Targets;
namespace MathGame.ObstacleFlow
{
    public sealed class ObstacleAnswerFlowRequest { public ObstacleAnswerFlowRequest(AnswerResult answer, StageAttemptId id, RefillValueRange refill, TargetHistory history, TargetRecoveryConfig config) { Answer=answer; AttemptId=id; Refill=refill; History=history; TargetConfig=config; } public AnswerResult Answer{get;} public StageAttemptId AttemptId{get;} public RefillValueRange Refill{get;} public TargetHistory History{get;} public TargetRecoveryConfig TargetConfig{get;} }
    public enum ObstacleAnswerFlowStatus { MissingRequest, InvalidStageState, NoPendingTargetProof, PendingTargetProofExists, MissingAnswer, MissingRefillRange, MissingHistory, MissingTargetConfig, ResolutionFailed, AttemptRejected, StageTerminal, TargetMissingInput, TargetInvalidConfiguration, TargetInvalidBoard, TargetSearchLimitExceeded, TargetShuffleFailed, TargetUnrecoverable, Succeeded }
    public sealed class ObstacleAnswerFlowResult { internal ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus s, MathGame.Board.Board b, int id, ObstacleResolutionResult r, StageAttemptResult a, FeverAttemptResult f, TargetRecoveryResult t, bool committed, bool ready) { Status=s;LogicalBoard=b;NextBlockIdValue=id;ResolutionResult=r;StageResult=a;FeverResult=f;TargetResult=t;AttemptCommitted=committed;IsInputReady=ready; } public ObstacleAnswerFlowStatus Status{get;} public MathGame.Board.Board LogicalBoard{get;} public int NextBlockIdValue{get;} public ObstacleResolutionResult ResolutionResult{get;} public StageAttemptResult StageResult{get;} public FeverAttemptResult FeverResult{get;} public TargetRecoveryResult TargetResult{get;} public bool AttemptCommitted{get;} public bool IsInputReady{get;} public TargetSolution SelectedTarget=>TargetResult?.Solution; public TargetHistory History=>TargetResult?.UpdatedHistory; }
    public sealed class ObstacleEndFlowRequest { public ObstacleEndFlowRequest(FeverEndResult end, BoardPosition? center, RefillValueRange refill, TargetHistory history, TargetRecoveryConfig config) { FeverEnd=end;Center=center;Refill=refill;History=history;TargetConfig=config; } public FeverEndResult FeverEnd{get;} public BoardPosition? Center{get;} public RefillValueRange Refill{get;} public TargetHistory History{get;} public TargetRecoveryConfig TargetConfig{get;} }
    public enum ObstacleEndFlowStatus { MissingRequest, InvalidStageState, PendingTargetProofExists, MissingFeverEndResult, MissingRefillRange, MissingHistory, MissingTargetConfig, MissingCenter, UnexpectedCenter, ResolutionFailed, StageSessionRejected, TargetMissingInput, TargetInvalidConfiguration, TargetInvalidBoard, TargetSearchLimitExceeded, TargetShuffleFailed, TargetUnrecoverable, StageTerminal, Succeeded }
    public sealed class ObstacleEndFlowResult { internal ObstacleEndFlowResult(ObstacleEndFlowStatus s, MathGame.Board.Board b, int id, ObstacleResolutionResult r, StageSystemEffectPrepareResult p, StageSystemEffectCommitResult c, TargetRecoveryResult t, bool committed, bool ready) {Status=s;LogicalBoard=b;NextBlockIdValue=id;ResolutionResult=r;PrepareResult=p;SystemEffectResult=c;TargetResult=t;EffectCommitted=committed;IsInputReady=ready;} public ObstacleEndFlowStatus Status{get;} public MathGame.Board.Board LogicalBoard{get;} public int NextBlockIdValue{get;} public ObstacleResolutionResult ResolutionResult{get;} public StageSystemEffectPrepareResult PrepareResult{get;} public StageSystemEffectCommitResult SystemEffectResult{get;} public TargetRecoveryResult TargetResult{get;} public TargetSolution SelectedTarget=>TargetResult?.Solution; public TargetHistory History=>TargetResult?.UpdatedHistory; public bool EffectCommitted{get;} public bool IsInputReady{get;} }
}
