using System;
using MathGame.Board;
using MathGame.BoardResolution;
using MathGame.Fever;
using MathGame.Stage;
using MathGame.StageSession;
using MathGame.Targets;
using MathGame.Restoration;
using MathGame.Restoration.Contracts;
using DomainBoard = MathGame.Board.Board;

namespace MathGame.ObstacleFlow
{
    public sealed class ObstacleResolutionCoordinator
    {
        readonly ObstacleBoardResolver resolver; readonly StageController stage; readonly MathGame.StageSession.StageSession session;
        readonly FeverController fever; readonly TargetRecoveryCoordinator targets; DomainBoard board; int nextId; bool pending;
        long gameplayRevision; long pendingSourceId; GameplayStateToken gameplayToken;
        readonly RestorationTransactionCoordinator restoration;
        public ObstacleResolutionCoordinator(ObstacleBoardResolver resolver, StageController stage, MathGame.StageSession.StageSession session, FeverController fever, TargetRecoveryCoordinator targets, DomainBoard initialBoard, int initialNextBlockId)
            : this(resolver,stage,session,fever,targets,initialBoard,initialNextBlockId,null) { }
        public ObstacleResolutionCoordinator(ObstacleBoardResolver resolver, StageController stage, MathGame.StageSession.StageSession session, FeverController fever, TargetRecoveryCoordinator targets, DomainBoard initialBoard, int initialNextBlockId, RestorationTransactionCoordinator restoration)
        { this.resolver=resolver??throw new ArgumentNullException(nameof(resolver));this.stage=stage??throw new ArgumentNullException(nameof(stage));this.session=session??throw new ArgumentNullException(nameof(session));this.fever=fever??throw new ArgumentNullException(nameof(fever));this.targets=targets??throw new ArgumentNullException(nameof(targets));this.restoration=restoration;if(initialBoard==null)throw new ArgumentNullException(nameof(initialBoard));if(!initialBoard.ValidateStable().IsStable||initialNextBlockId<=MaxId(initialBoard))throw new ArgumentException("Invalid handoff.");if(!fever.IsBoundTo(stage,session))throw new ArgumentException("Composition mismatch.");if(session.CreateSnapshot().StageRestorationCapacity>0&&restoration==null)throw new ArgumentException("Restoration coordinator required.");board=Clone(initialBoard);nextId=initialNextBlockId;gameplayRevision=1;gameplayToken=new GameplayStateToken(session.CreateSnapshot().StageRunId,gameplayRevision,GameplayStateSource.Initial,0); }
        public DomainBoard CurrentBoard=>Clone(board); public int NextBlockIdValue=>nextId;
        public GameplayStateToken CurrentGameplayToken=>gameplayToken;
        public GameplayStateSnapshot CaptureGameplayState()=>new GameplayStateSnapshot(gameplayToken,Clone(board),nextId);
        public bool IsCurrent(GameplayStateToken token)=>token==gameplayToken;
        public ObstacleAnswerFlowResult ResolveNormalAnswer(ObstacleAnswerFlowRequest q)=>Tag(Resolve(q,false));
        public ObstacleAnswerFlowResult ResolveFeverAnswer(ObstacleAnswerFlowRequest q)=>Tag(Resolve(q,true));
        ObstacleAnswerFlowResult Resolve(ObstacleAnswerFlowRequest q,bool feverMode)
        {
            var pre=PreflightAnswer(q); if(pre.HasValue)return Fail(pre.Value); var result=resolver.Resolve(feverMode?ObstacleResolutionRequest.FeverAnswer(board,q.Answer,q.Refill,nextId):ObstacleResolutionRequest.NormalAnswer(board,q.Answer,q.Refill,nextId));
            if(!result.Succeeded)return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.ResolutionFailed,null,0,result,null,null,null,false,false);
            StageAttemptResult applied; FeverAttemptResult feverResult=null;
            var snapshot=session.CreateSnapshot();RestorationAwardEvidence award=snapshot.StageRestorationCapacity>0?RestorationAwardCalculator.CreateAnswerEvidence(snapshot.StageRunId,q.AttemptId.Value,q.Answer.SelectedBlockCount,feverMode?StageAttemptMode.Fever:StageAttemptMode.Normal):null;
            if(feverMode){if(restoration!=null){var prepared=fever.PrepareFeverAttempt(q.AttemptId,q.Answer,result,award);feverResult=prepared.Plan==null?null:restoration.CommitPreparedFever(fever,prepared.Plan);}else feverResult=fever.ApplyFeverAttempt(q.AttemptId,q.Answer,result);applied=feverResult?.StageResult;if(feverResult==null||(feverResult.Status!=FeverAttemptApplyStatus.AppliedContinue&&feverResult.Status!=FeverAttemptApplyStatus.AppliedTerminal))return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.AttemptRejected,null,0,result,applied,feverResult,null,false,false);}
            else{if(restoration!=null){var prepared=session.PrepareAttempt(new StageAttemptCommand(q.AttemptId,q.Answer,result,StageAttemptRules.Normal,award),award);var committed=prepared.Plan==null?null:restoration.CommitPreparedAttempt(prepared.Plan);applied=committed?.StageResult?.Result;}else applied=session.ApplyAttempt(new StageAttemptCommand(q.AttemptId,q.Answer,result,StageAttemptRules.Normal));if(applied==null||(applied.Status!=StageAttemptApplyStatus.AppliedContinue&&applied.Status!=StageAttemptApplyStatus.AppliedSuccess&&applied.Status!=StageAttemptApplyStatus.AppliedFailure))return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.AttemptRejected,null,0,result,applied,null,null,false,false);}
            Adopt(result.Board,result.NextBlockIdValue,GameplayStateSource.Answer,q.AttemptId.Value);pending=true;pendingSourceId=q.AttemptId.Value;if(applied.After.Status!=StageSessionStatus.Active){pending=false;if(applied.After.Status==StageSessionStatus.FailedPendingDecision){if(stage.EnterFailedPendingDecision()!=TransitionResult.Succeeded)throw new InvalidOperationException("Failed decision transition rejected.");return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.FailedPendingDecision,Clone(board),nextId,result,applied,feverResult,null,true,false);}return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.StageTerminal,Clone(board),nextId,result,applied,feverResult,null,true,false);}return Recover(q.History,q.TargetConfig,result,applied,feverResult,true);
        }
        ObstacleAnswerFlowStatus? PreflightAnswer(ObstacleAnswerFlowRequest q){if(q==null)return ObstacleAnswerFlowStatus.MissingRequest;if(stage.State!=StageState.ResolvingAnswer||session.Status!=StageSessionStatus.Active||gameplayRevision==long.MaxValue)return ObstacleAnswerFlowStatus.InvalidStageState;if(pending)return ObstacleAnswerFlowStatus.PendingTargetProofExists;if(q.Answer==null)return ObstacleAnswerFlowStatus.MissingAnswer;if(q.Refill==null)return ObstacleAnswerFlowStatus.MissingRefillRange;if(q.History==null)return ObstacleAnswerFlowStatus.MissingHistory;if(q.TargetConfig==null)return ObstacleAnswerFlowStatus.MissingTargetConfig;return null;}
        public ObstacleAnswerFlowResult RetryTargetRecovery(TargetHistory h,TargetRecoveryConfig c)=>Tag(RetryTargetRecoveryCore(h,c));
        ObstacleAnswerFlowResult RetryTargetRecoveryCore(TargetHistory h,TargetRecoveryConfig c){if(stage.State!=StageState.ResolvingAnswer||session.Status!=StageSessionStatus.Active||gameplayRevision==long.MaxValue)return Fail(ObstacleAnswerFlowStatus.InvalidStageState);if(!pending)return Fail(ObstacleAnswerFlowStatus.NoPendingTargetProof);if(h==null)return Fail(ObstacleAnswerFlowStatus.MissingHistory);if(c==null)return Fail(ObstacleAnswerFlowStatus.MissingTargetConfig);return Recover(h,c,null,null,null,false);}
        ObstacleAnswerFlowResult Recover(TargetHistory h,TargetRecoveryConfig c,ObstacleResolutionResult r,StageAttemptResult a,FeverAttemptResult f,bool committed){var t=targets.SelectNextTarget(board,h,c);if(!t.Succeeded)return new ObstacleAnswerFlowResult(MapA(t.Status),Clone(board),nextId,r,a,f,t,committed,false);Adopt(t.Board,nextId,GameplayStateSource.TargetRecovery,pendingSourceId);pending=false;return new ObstacleAnswerFlowResult(ObstacleAnswerFlowStatus.Succeeded,Clone(board),nextId,r,a,f,t,committed,true);}
        public ObstacleEndFlowResult ResolveAndCommitEnd(ObstacleEndFlowRequest q)=>Tag(ResolveAndCommitEndCore(q));
        ObstacleEndFlowResult ResolveAndCommitEndCore(ObstacleEndFlowRequest q)
        {
            var pre=PreflightEnd(q);if(pre.HasValue)return EndFail(pre.Value);var pattern=Pattern(q.FeverEnd.EffectTier);var r=resolver.Resolve(ObstacleResolutionRequest.FeverEnd(board,pattern,session.CreateSnapshot().NextExpectedSystemEffectId,q.Center,q.Refill,nextId));if(!r.Succeeded)return new ObstacleEndFlowResult(ObstacleEndFlowStatus.ResolutionFailed,null,0,r,null,null,null,false,false);var snap=session.CreateSnapshot();RestorationAwardEvidence award=snap.StageRestorationCapacity>0&&pattern==FeverEndPattern.Large?RestorationAwardCalculator.CreateLargeEndEvidence(snap.StageRunId,r.SystemEffectId.Value):null;var p=session.PrepareSystemEffect(r,award);if(p.Plan==null)return new ObstacleEndFlowResult(ObstacleEndFlowStatus.StageSessionRejected,null,0,r,p,null,null,false,false);TargetRecoveryResult t=null;if(!p.Plan.WouldSucceed){t=targets.SelectNextTarget(r.Board,q.History,q.TargetConfig);if(!t.Succeeded)return new ObstacleEndFlowResult(MapE(t.Status),null,0,r,p,null,t,false,false);}var c=restoration!=null?restoration.CommitPreparedSystemEffect(p.Plan):session.CommitSystemEffect(p.Plan);if(c==null||(c.Status!=StageSystemEffectCommitStatus.CommittedContinue&&c.Status!=StageSystemEffectCommitStatus.CommittedSuccess))return new ObstacleEndFlowResult(ObstacleEndFlowStatus.StageSessionRejected,null,0,r,p,c,t,false,false);Adopt(t?.Board??r.Board,r.NextBlockIdValue,GameplayStateSource.SystemEffect,r.SystemEffectId.Value);pending=false;return new ObstacleEndFlowResult(c.Status==StageSystemEffectCommitStatus.CommittedSuccess?ObstacleEndFlowStatus.StageTerminal:ObstacleEndFlowStatus.Succeeded,Clone(board),nextId,r,p,c,t,true,c.Status==StageSystemEffectCommitStatus.CommittedContinue);
        }
        ObstacleEndFlowStatus? PreflightEnd(ObstacleEndFlowRequest q){if(q==null)return ObstacleEndFlowStatus.MissingRequest;if(stage.State!=StageState.EndingFever||session.Status!=StageSessionStatus.Active||gameplayRevision==long.MaxValue)return ObstacleEndFlowStatus.InvalidStageState;if(pending)return ObstacleEndFlowStatus.PendingTargetProofExists;if(q.FeverEnd==null)return ObstacleEndFlowStatus.MissingFeverEndResult;if(q.Refill==null)return ObstacleEndFlowStatus.MissingRefillRange;if(q.History==null)return ObstacleEndFlowStatus.MissingHistory;if(q.TargetConfig==null)return ObstacleEndFlowStatus.MissingTargetConfig;var spatial=q.FeverEnd.EffectTier==FeverEndEffectTier.SmallAreaExplosion||q.FeverEnd.EffectTier==FeverEndEffectTier.CenterAreaExplosion||q.FeverEnd.EffectTier==FeverEndEffectTier.LargeExplosionAndRestoration;if(spatial&&!q.Center.HasValue)return ObstacleEndFlowStatus.MissingCenter;if(!spatial&&q.Center.HasValue)return ObstacleEndFlowStatus.UnexpectedCenter;return null;}
        ObstacleAnswerFlowResult Fail(ObstacleAnswerFlowStatus s)=>new ObstacleAnswerFlowResult(s,null,0,null,null,null,null,false,false);ObstacleEndFlowResult EndFail(ObstacleEndFlowStatus s)=>new ObstacleEndFlowResult(s,null,0,null,null,null,null,false,false);
        static FeverEndPattern Pattern(FeverEndEffectTier t)=>t==FeverEndEffectTier.None?FeverEndPattern.None:t==FeverEndEffectTier.RandomThreeBlocks?FeverEndPattern.RandomThree:t==FeverEndEffectTier.SmallAreaExplosion?FeverEndPattern.Small:t==FeverEndEffectTier.CenterAreaExplosion?FeverEndPattern.Center:FeverEndPattern.Large;
        static ObstacleAnswerFlowStatus MapA(TargetRecoveryStatus s)=>s==TargetRecoveryStatus.MissingInput?ObstacleAnswerFlowStatus.TargetMissingInput:s==TargetRecoveryStatus.InvalidConfiguration?ObstacleAnswerFlowStatus.TargetInvalidConfiguration:s==TargetRecoveryStatus.InvalidBoardState?ObstacleAnswerFlowStatus.TargetInvalidBoard:s==TargetRecoveryStatus.SearchLimitExceeded?ObstacleAnswerFlowStatus.TargetSearchLimitExceeded:s==TargetRecoveryStatus.ShuffleFailed?ObstacleAnswerFlowStatus.TargetShuffleFailed:ObstacleAnswerFlowStatus.TargetUnrecoverable;
        static ObstacleEndFlowStatus MapE(TargetRecoveryStatus s)=>s==TargetRecoveryStatus.MissingInput?ObstacleEndFlowStatus.TargetMissingInput:s==TargetRecoveryStatus.InvalidConfiguration?ObstacleEndFlowStatus.TargetInvalidConfiguration:s==TargetRecoveryStatus.InvalidBoardState?ObstacleEndFlowStatus.TargetInvalidBoard:s==TargetRecoveryStatus.SearchLimitExceeded?ObstacleEndFlowStatus.TargetSearchLimitExceeded:s==TargetRecoveryStatus.ShuffleFailed?ObstacleEndFlowStatus.TargetShuffleFailed:ObstacleEndFlowStatus.TargetUnrecoverable;
        static int MaxId(DomainBoard b){var m=0;foreach(var p in b.EnumerateActivePositions()){b.TryGetCell(p,out var c);if(c.Block.HasValue)m=Math.Max(m,c.Block.Value.Id.Value);}return m;}
        void Adopt(DomainBoard adopted,int adoptedNextId,GameplayStateSource source,long sourceId){board=Clone(adopted);nextId=adoptedNextId;gameplayRevision=checked(gameplayRevision+1);gameplayToken=new GameplayStateToken(session.CreateSnapshot().StageRunId,gameplayRevision,source,Math.Max(0,sourceId));}
        ObstacleAnswerFlowResult Tag(ObstacleAnswerFlowResult result){if(result!=null)result.GameplayToken=gameplayToken;return result;}
        ObstacleEndFlowResult Tag(ObstacleEndFlowResult result){if(result!=null)result.GameplayToken=gameplayToken;return result;}
        static DomainBoard Clone(DomainBoard source){var boxes=new System.Collections.Generic.List<BoardPosition>();foreach(var p in source.EnumerateActivePositions()){source.TryGetCell(p,out var c);if(c.HasBox)boxes.Add(p);}var copy=new DomainBoard(BoardLayout.Create(source.Topology,boxes));foreach(var p in source.EnumerateActivePositions()){source.TryGetCell(p,out var c);if(c.HasBox)copy.TryPlaceBox(p,c.Box.Value);else{copy.TryPlaceBlock(p,c.Block.Value);if(c.HasDust)copy.TryPlaceDust(p,c.Dust.Value);}}return copy;}
    }
}
